// <auto-generated />
using Catedraticos.Connection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catedraticos.Migrations
{
    [DbContext(typeof(Conn))]
    partial class ConnModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catedraticos.Models.CatedraticoModel", b =>
                {
                    b.Property<int>("CodigoCatedratios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoCatedraticos")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<int>("EdadCatedratico")
                        .HasColumnType("int");

                    b.Property<string>("EstadoCatedratico")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("NombreCatedratico")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.HasKey("CodigoCatedratico");

                    b.ToTable("tbl_catedratico");
                });
#pragma warning restore 612, 618
        }
    }
}
